### ISSUE TITLE
style/api issues

### ISSUE THREAD

**Issue by sthalik** [gagagu/ftnoir_tracker_gvrs#1]
- You don't need to define SONAME <https://github.com/gagagu/ftnoir_tracker_gvrs/blob/master/ftnoir_tracker_gvrs.cpp#L8>, it's probably a remnant of the old plugin support stuff
- You can also use the UDP tracker here the same way you use aruco <https://github.com/gagagu/ftnoir_tracker_gvrs/blob/master/ftnoir_tracker_gvrs.cpp#L55>
- I haven't made the API to open a dialog window of a particular tracker public, but I can, to ease your configuration process. Later on, the dialog won't have OK/Cancel buttons and you'll be able to embed the Aruco configuration dialog inside your own dialog.
- You don't need to explicitly delete a smart pointer in the destructor. They'll delete themselves at the end of your destructor <https://github.com/gagagu/ftnoir_tracker_gvrs/blob/master/ftnoir_tracker_gvrs.cpp#L42>
- We now have an API for declaring plugins without all the `extern "C"` mess <https://github.com/gagagu/ftnoir_tracker_gvrs/blob/master/ftnoir_tracker_gvrs.cpp#L96>, see <https://github.com/opentrack/opentrack/blob/unstable/opentrack/plugin-api.hpp#L156>
- If you don't derive the settings struct from `opts`, it's gonna be left in indeterminate state when closing using the "X" button where settings apply to the tracker but aren't saved <https://github.com/gagagu/ftnoir_tracker_gvrs/blob/master/ftnoir_tracker_gvrs.h#L14>. See <https://github.com/opentrack/opentrack/blob/unstable/opentrack-compat/options.cpp#L192> for what it does.

If you have at least a minor user base (few thousand downloads), you can submit the plugin for review into including for opentrack, and be granted access rights.

sh

**Comment by gagagu** [comment]
Hi, sorry for the late reply, i am very busy atm. Thanks for the infos. I will make a newest version, soon.
Greetings
